#GLOBAL BUTTONS definitions
global_buttons_defs:
    #button name
    cursor: b-menu.png
    menu: b-menu.png
    menu-std: b-menu-std.png
    menu-sci: b-menu-sci.png
    menu-prog: b-menu-prog.png
    equal: b-=.png
    one: b-1.png
    two: b-2.png
    tree: b-3.png
    four: b-4.png
    five: b-5.png
    six: b-6.png
    seven: b-7.png
    height: b-8.png
    nine: b-9.png
    zero: b-0.png

#WINDOWS definitions
#name of window. 'main' is default and MUST be defined. Other windows names are free to choose.
main:   # Standard Calculator page
    #zones stored in coordinates
    zones:
        #zone name: its value. Coordinates are stored in a list.
        value: [0, 0, 552, 552]

    #BUTTONS definitions
    #global buttons
    global_buttons:
        # global button name from global_buttons_defs section.
        # And put the desired value for this window:
        # - normal, highlighted, disabled or all to use all states
        cursor: all

    #just buttons
    buttons:
        #button name and value is the name of png file
        percent: b-std-percent.png
