

# WINDOWS definitions
#     'main' is default and MUST be defined.
#     Other windows names are free to choose.

# Standard Calculator page
main:
    #zones defined by coordinates
    zones:
        #zone name: its value. Coordinates are stored in a list.
        calculator: [0, 0, 510, 790]
        screen: [15, 115, 500, 160]

    #Buttons defined by coordinates
    button_coord:
        # Template:
        # button_name:
        #     position: [y, y, w, h]
        menu:
            position: [ 10,  40, 40, 40]
        menu-std:
            position: [ 10,  40, 40, 40]
        menu-sci:
            position: [ 10,  40, 40, 40]
        menu-prog:
            position: [ 10,  40, 40, 40]

        # -------------------------------------
        one:
            position: [ 30, 640, 10, 10]
        two:
            position: [160, 640, 10, 10]
        three:
            position: [290, 640, 10, 10]
        plus:
            position: [480, 640, 10, 10]

        # -------------------------------------
        four:
            position: [ 30, 580, 10, 10]
        five:
            position: [160, 580, 10, 10]
        six:
            position: [290, 580, 10, 10]
        minus:
            position: [480, 580, 10, 10]

        # -------------------------------------
        seven:
            position: [ 30, 480, 10, 10]
        eight:
            position: [160, 480, 10, 10]
        nine:
            position: [290, 480, 10, 10]
        multiply:
            position: [480, 480, 10, 10]

        # -------------------------------------
        plusminus:
            position: [ 30, 720, 10, 10]
        zero:
            position: [160, 720, 10, 10]
        coma:
            position: [290, 720, 10, 10]
        equal:
            position: [480, 720, 10, 10]
